### ISSUE TITLE
Lower tensor dialect to LLVM backend

### ISSUE THREAD

**Issue by chhzh123** [makslevental/nelli#37]
Hi @makslevental, I'm a second-year PhD student at Cornell who has been following your projects and papers for a long time :) Thanks for open-sourcing your great project! The Python binding for MLIR is extremely helpful, and I learned a lot from Nelli and your other repositories.

Not sure if this is the right place to ask questions. Our group is building [something similar](https://github.com/cornell-zhang/heterocl) that lowers from a Python program to MLIR, but recently we encounter some issues when trying to lower the tensor dialect to the LLVM backend. Due to the limited documentation of MLIR, we are not sure whether this is the correct path. An example is to extract a slice from a tensor. The following code snippet shows retrieving the slice `A[1:2, 1:3]` from a 6x6 tensor `A`.

```mlir
module {
  func.func @slicing(%arg0: tensor<6x6xi32>) -> tensor<1x2xi32> {
    %extracted_slice = tensor.extract_slice %arg0[1, 1] [1, 2] [1, 1] : tensor<6x6xi32> to tensor<1x2xi32>
    return %extracted_slice : tensor<1x2xi32>
  }
}
```

We leverage the following pass to lower the module. My LLVM version is 18.x (commit [4706251](https://github.com/llvm/llvm-project/tree/llvmorg-18-init)).

```python
pm = PassManager.parse(
    "builtin.module(one-shot-bufferize{allow-return-allocs bufferize-function-boundaries},"
    "expand-strided-metadata, func.func(convert-linalg-to-affine-loops),lower-affine)"
)
```

It generates the MLIR module (just before lowering to LLVM) as follows. It seems it does not correctly capture the strides and offsets, which are dynamic in the module.

```mlir
module {
  func.func @slicing(%arg0: memref<6x6xi32, strided<[?, ?], offset: ?>>) -> memref<1x2xi32, strided<[?, ?], offset: ?>> {
    %base_buffer, %offset, %sizes:2, %strides:2 = memref.extract_strided_metadata %arg0 : memref<6x6xi32, strided<[?, ?], offset: ?>> -> memref<i32>, index, index, index, index, index
    %0 = arith.addi %offset, %strides#0 : index
    %1 = arith.addi %0, %strides#1 : index
    %reinterpret_cast = memref.reinterpret_cast %base_buffer to offset: [%1], sizes: [1, 2], strides: [%strides#0, %strides#1] : memref<i32> to memref<1x2xi32, strided<[?, ?], offset: ?>>
    return %reinterpret_cast : memref<1x2xi32, strided<[?, ?], offset: ?>>
  }
}
```

After feeding in the real inputs, it consistently returns the first part of the tensor no matter how we change the indices.

```python
# Numpy input
[[0 8 0 1 7 4]
 [8 3 5 0 2 5]
 [9 8 8 4 6 5]
 [0 5 1 5 5 8]
 [1 2 1 8 2 6]
 [4 5 1 8 1 4]]
# Expected
[[3 5]]
# Generated
[[0 8]]
```

I notice you have similar [test cases](https://github.com/makslevental/mlir-python-utils/blob/main/tests/test_tensor.py#L116-L140) for `tensor.extract_slice`, but only test if the generated IR is correct. I wonder whether you have fed the module to the LLVM execution engine to obtain the actual outputs? What is your lowering pass from tensor dialect to LLVM?

I would greatly appreciate it if you could use Nelli to execute this case on LLVM and see what would happen.

Many thanks,
Hongzheng

**Comment by makslevental** [comment]
Hello @chhzh123.

I haven't directly tried this (I will shortly) but I believe there might be some bugs having to do with strides and offsets for memref

https://discourse.llvm.org/t/setting-memref-elements-in-python-callback/72759

https://reviews.llvm.org/D157008

I will try this and let you know shortly.

**Comment by chhzh123** [comment]
Thanks for your pointer! It worked after I applied the patch in the thread! The bug is a bit tricky though.
